# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shot2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Travel',
            new_name='Item',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='product',
            new_name='item',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_hired',
            field=models.DateField(blank=True, null=True),
        ),
    ]
